int - int(input())
float - float(input())
str - input()
list of str - input().split()
tuple of strtuple(input().split())
set of str - set(input().split())
list of int - list (map(int,input().split()))
tuple of int - tuple (map(int,input().split()))
set of int - set(map(int,input().split()))Y
list of float - list (map(float,input().split()))
tuple of float - tuple (map(float,input().split()))
pet of float - set(map(float,input().split()))
